import Head from 'next/head'
import ChatDev from '../src/components/Chat' 
import { useAuth } from '../src/hooks/useAuth'


export default function Home(){

    const {user, handleSignIn } = useAuth()

    return (
      <>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
        </Head>
        {user ? <ChatDev/>  : <button onClick={handleSignIn}>login com o GitHub</button> }
    </>
      
    )
  }

