import Head from 'next/head'
import styled from '../styles/Login.module.scss'
import { getSession, signIn } from 'next-auth/react'
import { AiFillGithub } from 'react-icons/ai'

export const getServerSideProps = async ({ req }: any) => {

  const session = await getSession({ req });

  if (session) {
    return {
      redirect: {
        destination: '/chat',
        permanent: false,
      }
    }
  }

  return {
    props: {}
  }
}

export default function Home(){

   const handleSignIn = async () => signIn("github") 

    return (
      <>
        <Head>
          <title>Login ChatDev</title>
          <meta name="description" content="Generated by create next app" />
        </Head>
          <main className={styled.LoginContainer}>

            <div className={styled.conteinerLogo}>
              <p className={styled.openTag}>{'<'}</p><span className={styled.logo}>Chat<p>Dev{'>'}</p></span>
            </div>

            <button onClick={handleSignIn}>
              <AiFillGithub color='#fff' size={32}/>
              <span>Login com o GitHub</span>
            </button> 
          </main>
      </>
    )
  }

